
apiVersion: v1     
kind: Pod                               
metadata:           
  name: vault-mock
  labels:
    vault-initialized: "true"

spec:               
  containers:
  - name: webserver  
    image: nginx:latest 
    ports:               
    - containerPort: 80
