
apiVersion: v1     
kind: Pod                               
metadata:           
  name: gitlab-mock
  labels:
    app: webservice

spec:               
  containers:
  - name: webserver  
    image: nginx:latest 
    ports:               
    - containerPort: 80
